import Head from 'next/head'
import { Inter } from '@next/font/google'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import axios from 'axios';
// import { createStytchHeadlessClient } from '@stytch/nextjs/headless';
// import { StytchProvider } from '@stytch/nextjs';

const inter = Inter({ subsets: ['latin'] })
const query = new QueryClient();
// const stytchClient = createStytchHeadlessClient(process.env.STYTCH_PUBLIC_TOKEN);

import { Header, Home } from '../components'

export default function Index(props) {
  return (
    <>
      <Head>
        <title>Ecom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={query}>
        {/* <StytchProvider stytch={stytchClient}> */}
        <main className='min-h-screen max-w-screen bg-black'>
          <div className="app mx-auto max-w-[70rem]">
            <Header />
            <Home props={props} />
          </div>
        </main>
        {/* </StytchProvider> */}
      </QueryClientProvider>
    </>
  )
};

export async function getStaticProps(context) {
  const { data } = await axios.get('https://dummyjson.com/products?limit=100');
  return {
    props: data
  };
};

